name: smart_task_manager
description: A Smart Task Manager demonstrating HTTP POST/GET with Dio and Clean Architecture
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Configuration to generate app launcher icons from assets/images/tarea.png
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/mi_logo.png"

# Configuration for native splash screen using the same image
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/mi_logo.png
  android: true
  ios: false
  web: true
  android_gravity: center
  ios_content_mode: center
